import React, { Component } from 'react';
import './title-section.css';

class TitleSection extends Component {
    render() {
        return (
            <div class="row">
                <div class="col-xs-offset-2 col-xs-8">
                    <h1>Are We Human<br/>Or Are We Chatbot?</h1>
                </div>
                <div class="col-xs-offset-2 col-xs-8 about-box">
                    <div class="row">
                        <div class="col-xs-6">
                            <h2>About</h2>
                            <p>“Are We Human Or Are We Chatbot?” is an algorithmically generated video series that explores the interactions between humans and chatbots.</p>
                        </div>
                        <div class="col-xs-6">
                            <h2>How They’re Made</h2>
                            <p>The dialogue is scraped from the logs of a French chatbot and translated to English. The actors are randomly selected stock photos. The voices are generated by Google Translate.</p>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default TitleSection;
